# Generated by Django 5.1.3 on 2024-11-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='usertogroup',
            index=models.Index(fields=['user_id'], name='service_use_user_id_dac44a_idx'),
        ),
        migrations.AddIndex(
            model_name='usertogroup',
            index=models.Index(fields=['group'], name='service_use_group_i_12aca1_idx'),
        ),
    ]
